blank_issues_enabled: false
contact_links:
  - name: Announcing Agent TARS App (Preview)
    url: https://agent-tars.com/2025/03/18/announcing-agent-tars-app
    about: An open-source multimodal AI agent Offering seamless integration with a wide range of real-world tools.
