# .github/workflows/build-and-push-image.yml
name: Build & Publish UI to GHCR

on:
  push:
    branches: [ main ]

permissions:
  contents: read      # ソースコードを checkout するため
  packages: write     # GHCR にプッシュするため
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU (マルチアーキ用)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # ここは GITHUB_TOKEN でも、CR_PAT でも OK
          # 組織設定で write 権限が取れるなら GITHUB_TOKEN を…
          # 取りづらければ secrets.CR_PAT を使う
          password: ${{ secrets.CR_PAT }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.ui
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ui-tars:latest
            ghcr.io/${{ github.repository_owner }}/ui-tars:${{ github.sha }}
