# .github/workflows/build-and-push-image.yml
name: Build & Publish UI to GHCR

on:
  push:
    branches:
      - main

permissions:
  contents: read    # ソースコードをチェックアウトするため
  packages: write   # GHCR にイメージをプッシュするため

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1) リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) マルチアーキ用 QEMU をセットアップ（省略可）
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 3) Buildx をセットアップ
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4) GHCR にログイン（組み込みの GITHUB_TOKEN を使用）
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      # 5) Dockerfile.ui をビルド＆プッシュ
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
             VITE_OPENAI_API_KEY=${{ secrets.VITE_OPENAI_API_KEY }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/ui-tars:latest
            ghcr.io/${{ github.repository_owner }}/ui-tars:${{ github.sha }}

  trigger-render:
    name: Trigger Render Deploy
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Notify Render to redeploy
        run: |
          curl -X POST -d '' "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"