name: Build & Publish UI to GHCR

on:
  push:
    branches: [ main ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Install & Build UI
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |
          pnpm install
          pnpm --filter ./apps/agent-tars run build:web

      - name: Generate npm lockfile
        working-directory: apps/agent-tars
        run: npm install --package-lock-only

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.ui
          push: true
          tags: |
            ghcr.io/wabisabiinc/ui-tars:latest
            ghcr.io/wabisabiinc/ui-tars:${{ github.sha }}
