on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'main'

name: CI E2E
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-test
  cancel-in-progress: true
env:
  CI: e2e
  NODE_OPTIONS: --max-old-space-size=8192
  HUSKY: 0

permissions:
  id-token: write
  contents: read
  attestations: read

jobs:
  e2e:
    name: E2E
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install pnpm
        run: npm install -g pnpm@9
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install Python setuptools
        if: matrix.os == 'macos-latest'
        run: brew install python-setuptools
      - name: Install appdmg
        if: matrix.os == 'macos-latest'
        run: npm install -g appdmg
      - name: Install dependencies
        run: pnpm install
      - name: Run e2e
        run: pnpm run test:e2e
